"""'tariff_2'

Revision ID: 349695fca431
Revises: d70aa16d7762
Create Date: 2024-04-10 15:44:33.120878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '349695fca431'
down_revision = 'd70aa16d7762'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_table_tariff_fkey', 'users_table', type_='foreignkey')
    op.drop_column('users_table', 'tariff')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_table', sa.Column('tariff', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_table_tariff_fkey', 'users_table', 'tariffs_table', ['tariff'], ['id'])
    # ### end Alembic commands ###
