"""'user_banned'

Revision ID: 6475a8bbbe39
Revises: 9f661b736e1f
Create Date: 2024-04-07 22:48:06.830130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6475a8bbbe39'
down_revision = '9f661b736e1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_table', sa.Column('banned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_table', 'banned')
    # ### end Alembic commands ###
