"""'Parking_count'

Revision ID: bbd1b831e087
Revises: cbeec90c3818
Create Date: 2024-04-11 13:01:09.149104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbd1b831e087'
down_revision = 'cbeec90c3818'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_count_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('ococcupied_quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parking_count_table')
    # ### end Alembic commands ###
