"""'tariff_3'

Revision ID: c543ceb93af1
Revises: 349695fca431
Create Date: 2024-04-10 15:53:23.206927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c543ceb93af1'
down_revision = '349695fca431'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_table', sa.Column('tariff_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users_table', 'tariffs_table', ['tariff_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_table', type_='foreignkey')
    op.drop_column('users_table', 'tariff_id')
    # ### end Alembic commands ###
