"""'tariff_5'

Revision ID: cbeec90c3818
Revises: c543ceb93af1
Create Date: 2024-04-10 15:59:37.186039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbeec90c3818'
down_revision = 'c543ceb93af1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariffs_table', sa.Column('tariff_name', sa.String(length=30), nullable=False))
    op.add_column('tariffs_table', sa.Column('tariff_value', sa.Numeric(), nullable=True))
    op.drop_constraint('tariffs_table_tarriff_name_key', 'tariffs_table', type_='unique')
    op.create_unique_constraint(None, 'tariffs_table', ['tariff_name'])
    op.drop_column('tariffs_table', 'tarriff_name')
    op.drop_column('tariffs_table', 'tarriff_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariffs_table', sa.Column('tarriff_value', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('tariffs_table', sa.Column('tarriff_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tariffs_table', type_='unique')
    op.create_unique_constraint('tariffs_table_tarriff_name_key', 'tariffs_table', ['tarriff_name'])
    op.drop_column('tariffs_table', 'tariff_value')
    op.drop_column('tariffs_table', 'tariff_name')
    # ### end Alembic commands ###
