"""'init'

Revision ID: 53489f9a3801
Revises: 
Create Date: 2024-04-06 23:06:52.943292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53489f9a3801'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_plate', sa.String(length=30), nullable=False),
    sa.Column('banned', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_plate')
    )
    op.create_table('parking_places_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enter_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('places_quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('lcense_plate', sa.String(length=30), nullable=True),
    sa.Column('amount_paid', sa.Numeric(), nullable=True),
    sa.Column('duration', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['lcense_plate'], ['cars_table.license_plate'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('lcense_plate', sa.String(length=30), nullable=True),
    sa.CheckConstraint("role IN ('admin', 'user')", name='check_valid_role'),
    sa.ForeignKeyConstraint(['lcense_plate'], ['cars_table.license_plate'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('lcense_plate'),
    sa.UniqueConstraint('username')
    )
    op.create_table('blacklisted_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blacklisted_token', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklisted_tokens')
    op.drop_table('users_table')
    op.drop_table('parking_places_table')
    op.drop_table('cars_table')
    # ### end Alembic commands ###
